### ISSUE TITLE
uploading fail

### ISSUE THREAD

**Issue by hamilton5** [Source2ZE/AcceleratorCS2#3]
How can I figure out why my dumps are not getting uploaded - Or the reason for "Whoops, looks like something went wrong."? Dashboard says uploaded but going to the ID gives that message. These are things I can see in the server console:

```
Upload response:
Uploading minidump /home/steam/counterstrike2/game/csgo/addons/AcceleratorCS2/dumps/67cb2c68-3dc3-4de7-795b99a1-4130a223.dmp
Upload response: Crash ID: PXME-LSTZ-CTR6
```

```
Failed to open curl lib from binary, use libcurl.so instead
Failed to send http request to http://crash.limetech.org/symbols/submit, error: HTTP response code said error
Failed to open curl lib from binary, use libcurl.so instead
```

**Comment by Vauff** [comment]
The cause of this was AcceleratorCS2 needing an SDK rebuild, it was grabbing a garbage map name and sending it to the Accelerator backend, which was rejecting it. This has been fixed for a while now though.
