### ISSUE TITLE
Failed load 

### ISSUE THREAD

**Issue by szogun1910** [Source2ZE/AcceleratorCS2#5]
Metamod:Source version 2.0.0-dev+1314
Failed to load plugin addons/AcceleratorCS2/AcceleratorCS2 (/home/container/game/csgo/addons/AcceleratorCS2/AcceleratorCS2.so: undefined symbol: AssertValidStringPtr).

**Comment by Vauff** [comment]
[v2.0.3](https://github.com/Source2ZE/AcceleratorCS2/releases/tag/v2.0.3) is now released to fix this.
